import React, { useState } from "react";

const CitiesAndCountries = () => {
	const [citiesAndCountries, setCitiesAndCountries] = useState([
		"Lagos, Nigeria",
		"Mumbai, India",
		"Beijing, China",
		"London, United Kingdom",
		"New York City, United States",
		"São Paulo, Brazil",
		"Tokyo, Japan",
		"Cairo, Egypt",
		"Sydney, Australia",
		"Moscow, Russia",
		"Paris, France",
		"Toronto, Canada",
		"Johannesburg, South Africa",
		"Mexico City, Mexico",
		"Dubai, United Arab Emirates",
		"Berlin, Germany",
		"Bangkok, Thailand",
		"Rome, Italy",
		"Singapore, Singapore",
		"Seoul, South Korea",
		"Istanbul, Turkey",
		"Stockholm, Sweden",
		"Madrid, Spain",
		"Lima, Peru",
		"Buenos Aires, Argentina",
		"Amsterdam, Netherlands",
		"Vienna, Austria",
		"Athens, Greece",
		"Copenhagen, Denmark",
		"Oslo, Norway",
		"Helsinki, Finland",
		"Prague, Czech Republic",
		"Warsaw, Poland",
		"Budapest, Hungary",
		"Lisbon, Portugal",
		"Brussels, Belgium",
		"Zurich, Switzerland",
		"Dublin, Ireland",
		"Brasília, Brazil",
		"Riyadh, Saudi Arabia",
		"Abu Dhabi, United Arab Emirates",
		"Doha, Qatar",
		"Kuwait City, Kuwait",
		"Manama, Bahrain",
		"Muscat, Oman",
		"San Francisco, United States",
		"Los Angeles, United States",
		"Chicago, United States",
		"Houston, United States",
		"Philadelphia, United States",
		"Phoenix, United States",
		"San Diego, United States",
		"Dallas, United States",
		"San Antonio, United States",
		"Seattle, United States",
		"Denver, United States",
		"Las Vegas, United States",
		"Atlanta, United States",
		"Miami, United States",
		"Boston, United States",
		"Minneapolis, United States",
		"Detroit, United States",
		"Tampa, United States",
		"Orlando, United States",
		"New Orleans, United States",
		"Denver, United States",
		"Salt Lake City, United States",
		"Portland, United States",
		"Vancouver, Canada",
		"Calgary, Canada",
		"Edmonton, Canada",
		"Montreal, Canada",
		"Ottawa, Canada",
		"Quebec City, Canada",
		"Toronto, Canada",
		"Winnipeg, Canada",
		"Vancouver, Canada",
		"Halifax, Canada",
		"St. John's, Canada",
		"Sydney, Canada",
		"Saint Petersburg, Russia",
		"Kiev, Ukraine",
		"Minsk, Belarus",
		"Warsaw, Poland",
		"Bucharest, Romania",
		"Sofia, Bulgaria",
		"Belgrade, Serbia",
		"Zagreb, Croatia",
		"Athens, Greece",
		"Budapest, Hungary",
		"Vienna, Austria",
		"Prague, Czech Republic",
		"Berlin, Germany",
		"Hamburg, Germany",
		"Munich, Germany",
		"Cologne, Germany",
		"Frankfurt, Germany",
		"Stuttgart, Germany",
		"Dusseldorf, Germany",
		"Amsterdam, Netherlands",
		"Rotterdam, Netherlands",
		"The Hague, Netherlands",
		"Brussels, Belgium",
		"Antwerp, Belgium",
		"Luxembourg City, Luxembourg",
		"Geneva, Switzerland",
		"Zurich, Switzerland",
		"Bern, Switzerland",
		"Milan, Italy",
		"Naples, Italy",
		"Rome, Italy",
		"Florence, Italy",
		"Venice, Italy",
		"Madrid, Spain",
		"Barcelona, Spain",
		"Valencia, Spain",
		"Lisbon, Portugal",
		"Porto, Portugal",
		"Dublin, Ireland",
		"Cork, Ireland",
		"Belfast, United Kingdom",
		"Glasgow, United Kingdom",
		"Edinburgh, United Kingdom",
		"Manchester, United Kingdom",
		"Birmingham, United Kingdom",
		"Leeds, United Kingdom",
		"Newcastle upon Tyne, United Kingdom",
		"Sheffield, United Kingdom",
		"Liverpool, United Kingdom",
		"Bristol, United Kingdom",
		"Cardiff, United Kingdom",
		"Bristol, United Kingdom",
		"Birmingham, United Kingdom",
		"Manchester, United Kingdom",
		"Leeds, United Kingdom",
		"Newcastle upon Tyne, United Kingdom",
		"Sheffield, United Kingdom",
		"Liverpool, United Kingdom",
		"Bristol, United Kingdom",
		"Cardiff, United Kingdom",
		"Amman, Jordan",
		"Jerusalem, Israel",
		"Tel Aviv, Israel",
		"Beirut, Lebanon",
		"Istanbul, Turkey",
		"Ankara, Turkey",
		"Izmir, Turkey",
		"Baku, Azerbaijan",
		"Tbilisi, Georgia",
		"Yerevan, Armenia",
		"Tehran, Iran",
		"Baghdad, Iraq",
		"Kuwait City, Kuwait",
		"Doha, Qatar",
		"Riyadh, Saudi Arabia",
		"Jeddah, Saudi Arabia",
		"Mecca, Saudi Arabia",
		"Medina, Saudi Arabia",
		"Dubai, United Arab Emirates",
		"Abu Dhabi, United Arab Emirates",
		"Muscat, Oman",
		"Sanaa, Yemen",
		"Addis Ababa, Ethiopia",
		"Nairobi, Kenya",
		"Kampala, Uganda",
		"Dar es Salaam, Tanzania",
		"Lusaka, Zambia",
		"Harare, Zimbabwe",
		"Gaborone, Botswana",
		"Windhoek, Namibia",
		"Pretoria, South Africa",
		"Johannesburg, South Africa",
		"Cape Town, South Africa",
		"Durban, South Africa",
		"Port Elizabeth, South Africa",
		"Bloemfontein, South Africa",
		"Antananarivo, Madagascar",
		"Nouakchott, Mauritania",
		"Bamako, Mali",
		"Banjul, Gambia",
		"Dakar, Senegal",
		"Freetown, Sierra Leone",
		"Monrovia, Liberia",
		"Conakry, Guinea",
		"Bissau, Guinea-Bissau",
		"Praia, Cape Verde",
		"Dakar, Senegal",
		"Nouakchott, Mauritania",
		"Bamako, Mali",
		"Banjul, Gambia",
		"Dakar, Senegal",
		"Freetown, Sierra Leone",
		"Monrovia, Liberia",
		"Conakry, Guinea",
		"Bissau, Guinea-Bissau",
		"Praia, Cape Verde",
		"Nouakchott, Mauritania",
	]);
	return citiesAndCountries;
};

export default CitiesAndCountries;
