import { useState } from "react";

const Jobs = () => {
	const [jobs, setJobs] = useState([
		"Software Engineer",
		"Data Scientist",
		"Network Administrator",
		"Web Developer",
		"DevOps Engineer",
		"Systems Analyst",
		"Database Administrator",
		"UI/UX Designer",
		"Machine Learning Engineer",
		"Cloud Solutions Architect",
		"Cybersecurity Analyst",
		"Mobile App Developer",
		"Frontend Developer",
		"Backend Developer",
		"fullstack developer",
		"Game Developer",
		"IT Project Manager",
		"Project Manager",
		"Marketing Manager",
		"Financial Analyst",
		"Human Resources Manager",
		"Operations Manager",
		"Sales Manager",
		"Accountant",
		"Supply Chain Manager",
		"Product Manager",
		"Data Analyst",
		"Market Research Analyst",
		"Business Consultant",
		"Investment Analyst",
		"Risk Analyst",
		"Hardware Engineer",
		"Automation Engineer",
		"Systems Integrator",
		"IT Security Analyst",
		"Data Warehouse Developer",
		"VR/AR Developer (Virtual Reality/Augmented Reality)",
		"Software Development Manager",
		"IT Trainer",
		"SAP Consultant",
		"Linux Administrator",
		"Wireless Network Engineer",
		"IT Auditor",
		"Technical Writer",
		"Graphic Designer",
		"Visual Designer",
		"UI-UX Designer",
		"Illustrator",
		"Art Director",
		"Web Designer",
		"Motion Graphics Designer",
		"Brand Designer",
		"Logo Designer",
		"Packaging Designer",
	]);
	return jobs;
};

export default Jobs;
