import { useState } from "react";

const SkillsList = () => {
	const [skills, setSkills] = useState([
		"JavaScript",
		"Node js",
		"Python",
		"Django",
		"Flask",
		"Java",
		"Sping Boot",
		"C++",
		"Web Development",
		"HTML5",
		"CSS3",
		"Database Management",
		"Mongo DB",
		"MySQL",
		"PostgreSQL",
		"Network Administration",
		"Cybersecurity",
		"Cloud Computing",
		"DevOps",
		"Linux and Windows Operating Systems",
		"IT Support",
		"Data Analysis",
		"Machine Learning and AI",
		"Web and Mobile App Development",
		"React Natieve",
		"Git",
		"Project Management",
		"Mobile Device Management",
		"Virtualization",
		"IoT",
		"Big Data and Hadoop",
		"Software Testing and Quality Assurance",
		"Blockchain Development",
		"Shell Scripting",
		"Computer Hardware Troubleshooting",
		"Cloud Security",
		"Containerization",
		"Network Security",
		"Scripting Languages",
		"API Integration",
		"UI/UX Design Principles",
		"Server Administration",
		"CI/CD Tools",
		"RESTful API Design",
		"Data Visualization (D3.js, Tableau)",
		"Full Stack Development",
		"Microsoft Office Suite",
		"E-commerce Development",
		"NoSQL Databases",
		"Microservices Architecture",
		"Wireframing and Prototyping",
		"Search Engine Optimization",
		"Responsive Web Design",
		"Agile Software Development",
		"Web Security",
		"Content Management Systems",
		"Technical Writing and Documentation",
		"User Research and Testing",
		"Vue.js",
		"React",
		"Angular",
		"Back-End Frameworks",
		"express JS",
		"PHP Development",
		"Swift Development",
		"Go Development",
		"Rust Development",
		"Scala Development",
		"Kotlin Development",
		"Dart Development",
		"Assembly Language",
		"MATLAB Programming",
		"Perl Scripting",
		"TypeScript",
		"Objective-C Development",
		"COBOL Programming",
		"Fortran Programming",
		"PL/SQL",
		"Lua Scripting",
		"Groovy Scripting",
		"VHDL Programming",
		"Clojure Development",
		"R Programming",
		"PowerShell Scripting",
		"Scala Programming",
		"Erlang Programming",
		"Haskell Development",
		"Julia Programming",
		"Prolog Programming",
		"Scratch Programming",
		"SQL Querying",
		"Shell Scripting",
		"Mobile App Development",
		"Windows Server Management",
		"Linux Server Management",
		"Apache Kafka",
		"Data Warehousing",
		"Agile Project Management",
		"Embedded Systems Programming",
		"Adobe Photoshop",
		"Adobe Illustrator",
		"Adobe InDesign",
		"Adobe Creative Cloud Suite",
		"Typography",
		"Color Theory",
		"Layout and Composition",
		"Digital Illustration",
		"Photo Editing",
		"Print Design",
		"UI/UX Design",
		"Brand Identity",
		"3D Modeling and Animation",
		"Video Editing",
		"Illustration and Digital Painting",
		"Motion Graphics",
		"Logo Design",
		"Packaging Design",
		"Visual Communication",
		"Storyboarding",
		"Vector Graphics",
		"Infographic Design",
		"Interactive Media Design",
		"User Interface Design",
		"User Experience Design",
		"Game Design",
		"3D Printing",
		"Augmented Reality",
		"Virtual Reality",
		"Poster Design",
		"Brochure Design",
		"Icon Design",
		"Publication Layout",
		"Social Media Graphics",
		"CAD",
		"Environmental Design",
		"Fashion Design",
		"Character Design",
		"Responsive Design",
		"Print Production",
		"Sculpture and Modeling",
		"Photography",
		"Storyboarding",
		"Wireframing and Prototyping",
		"Client Communication",
		"Portfolio Development",
	]);

	return skills;
};

export default SkillsList;
